name: 'Pull Request Size'
description: 'Attach a label representing the size of Pull Request'
author: 'Kazumasa Kohtaka <kkohtaka@gmail.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-pull-request'
  color: 'blue'
